
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    region="us-west-2"
    file_path="s3-bucket.tf"
    contents=$(cat ${file_path} | jq '.' -MRs)
    payload="{\"data\":{\"attributes\":{\"type\":\"cloudformation-template\",\"contents\":${contents}}}}"

    echo Request:
    echo ${payload} | jq '.' -M

    echo Response:
    curl -s -X POST \
        -H "Authorization: ApiKey $(C1 API Secret)" \
        -H "Content-Type: application/vnd.api+json" \
        https://conformity.$(region).cloudone.trendmicro.com/api/template-scanner/scan \
        --data-binary "${payload}" | jq '.' -M
  displayName: 'Scan Terraform Template'